# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-06 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20190906_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='creator',
            field=models.CharField(default=1, editable=False, max_length=128, verbose_name='\u521b\u5efa\u4eba'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='review',
            name='utime',
            field=models.DateTimeField(editable=False, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
    ]
